services:
  # A Docker web service
  - type: web
    name: langflow
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/logspace-ai/langflow
    branch: main
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: sqlite:////home/user/.cache/langflow/langflow.db
    disk:
      name: langflow-data
      mountPath: /home/user/.cache/langflow
